### ISSUE TITLE
tea.js中存在大量语句不规范的问题，该有分号的没分号，该有括号的没括号

### ISSUE THREAD

**Issue by dot888** [island205/HelloSea.js#33]

**Comment by afc163** [comment]
所以楼主是分号党？坐等无分号党现身

**Comment by dot888** [comment]
这样容易报错啊，代码要稍微严谨一点点嘛，我用编辑器打开,jshint报一堆错

**Comment by island205** [comment]
我不喜欢写分号。没有没分号容易报错这一说。至于你的 jshint一堆报错，并不代表运行时会报错。jshint可以配置不要求加分号。

其次如果你是来学习模块加载器是如何工作的，支持你！如果你想找一个模块加载器，那我希望你不要用 requirejs、不要用seajs，更不要用这个。你倒是可以考虑考虑 https://github.com/systemjs/systemjs

**Comment by dot888** [comment]
您好，你对seajs怎么看，我用了下，感觉还不错呀，没有命名空间方面的顾虑了，直接以模块化来开展工作了。  就是学习的资料不够系统 比较杂。

**Comment by island205** [comment]
@dot888 放几年前，我觉得 SeaJS 不是一个不错的选择。但随着 JavaScript 的发展，有了新的模块化标准，我们就应该向新的模块化标准看齐。所以我推荐你看看 https://github.com/systemjs/systemjs。如果你非要选择 SeaJS，那我推荐你用 RequireJS，又更多的人知道 AMD，更多的类库支持 AMD；我使用下来，痛点不大，倒是看到一些人使用 SeaJS 犯迷糊的。

**Comment by zquancai** [comment]
SeaJS也还好吧，国内的东西，犯迷糊很多是路径没搞对，这个的话SeaJS确实没做好。不过对于初步接触模块化的同学还是比较容易理解的。要是给个全英文的文档，英语基础差点的就有阻力了。
