### ISSUE TITLE
通过toString获取源代码，然后匹配出依赖的模块，那么通过if判断来加载的模块怎么弄呢？

### ISSUE THREAD

**Issue by aifengzi** [island205/HelloSea.js#37]
像这样：
if ( flag ) {
        var a = require( './a' );
        a.doSomething();
}
如果 flag 是false， 通过正则匹配后，加载模块a后，a并没有执行，那么a模块是不是白加载了 ？求解

**Comment by island205** [comment]
是的，Sea.js 存在这种问题。在 Node.js 中则不会出现。
